#! /usr/bin/env ruby

require 'Qt'
require 'rock/bundles'
require 'vizkit'
Bundles.setup_search_paths
require 'rock_auv/auv_control_calibration/ui'
require 'rock_auv/auv_control_calibration/ui/dumb_z_controller'
Orocos.initialize

z_controller = Orocos::Async.proxy 'auv_control_world_pose2body_effort'
pose         = Orocos::Async.proxy 'gazebo:underwater:flat_fish'
syskit = Roby::Interface::Async.new
w = RockAUV::AUVControlCalibration::Ui::DumbZController.monitor(pose, z_controller, syskit)
w.resize 1024,768
w.show

syskit_poll = Qt::Timer.new
syskit_poll.connect(SIGNAL('timeout()')) do
    syskit.poll
end
syskit_poll.start(10)
Vizkit.exec

