require "models/compositions/control_cascade"
require "models/compositions/constant_setpoint_generator"
require "models/compositions/stable_pitch_roll"
require "models/compositions/constant_setpoint_generators"
require "models/compositions/trajectory_follower"
